### ISSUE TITLE
As a patient I need to zoom the map visualization so that I can navigate the data.

### ISSUE THREAD

**Issue by adphillips2017** [cns-iu/spoke-vis#13]
Ensure the patient can zoom the map visualization in order to navigate the data by providing:

- [ ]  A plus icon that increase zoom when clicked
- [ ]  A minus icon that decreases zoom when clicked
- [ ]  Plus and minus icons that zoom the map in and out, respectively, when clicked
- [ ]  A PIP at the bottom right of the browser window that has a red outline that sizes and positions to indicate where the user currently is on the map
- [ ]  A scale that shows the current zoom level (e.g. 1x, 2x, 3x, etc)

**Comment by adphillips2017** [comment]
Hey @lecross could you provide clarity on exactly what the scalebar shows and when.

**Comment by lecross** [comment]
The scale bar shows the current scale of the zoom. Bruce has details about what needs to be done and how he wants to do it; at least that was my take-away from our meeting with Katy. Katy wanted to see magnification type information, 1x, 2x, 3x, etc. I'm not sold on the scale bar because visual confirmation of scale is provided in the PIP. You have a small rectangle showing when zoomed in and one that goes to the borders of the PIP when zoomed out. To me that indicates scale. In its current implementation, the scale bar is nothing but a frame for the magnification level. Technically, the bar should size from full width of PIP down with each step in magnification level. If that technique is used, then the number for magnification needs to sit outside the bar's confines. This is probably an issue that will require Bruce and I talk. What is possible in Vega applies constraints that I don't know.
________________________________

**Comment by bherr2** [comment]
I get showing what zoom level its at, but I don't know what the width of the bar should look like/be exactly.

@adphillips2017 obviously, the scale bar is lowest on the priority list for this feature
@lecross also just FYI, this component is being written with Mapbox, not Vega-Lite

**Comment by lecross** [comment]
Adam, Bruce and I will meet around 1:00PM ET to discuss. You'll have an answer by 1:30PM. That is the soonest he is available.
________________________________

**Comment by lecross** [comment]
Adam,

Bruce and I met and had a lengthy discussion about the pros and cons of various approaches, and about what the component is supposed to accomplish. What was agreed to was to keep this item in the backlog,  that we would address it at a later date. Katy needs to weigh in. She is traveling today to Germany, thus will be offline today and potentially several days.
________________________________

**Comment by lecross** [comment]
Adam,

I managed to get through to Katy. We only need the zoom level number. In the documentation I updated Page 15. No scale bar. Add the zoom level indicator using whichever method is easier to implement. There is the potential that the zoom controls will get reworked later into a slider which may impact how all this functions together. For now, the user just needs to see the zoom level. Talk to Bruce about where to put this in your priorities.

[cid:aa872bb3-9eb9-4f90-abd5-65050fbbe36b]
________________________________
